version: '3.9'  # Specify Docker Compose version

services:
  # Django Ninja API service
  app:
    build: .  # Build the Django project from the current directory
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000 (adjust if needed)
    volumes:
      - .:/app  # Mount the current directory (project code) into the container
    environment:
      - DATABASE_NAME=dj_movie  # Database name
      - DATABASE_USER=admin  # Database user
      - DATABASE_PASSWORD=postgres  # Database password 
      - DATABASE_HOST=db  # Database hostname 
    depends_on:
      - db

  # PostgreSQL database service
  db:
    image: postgres:latest  # Use the latest official PostgreSQL image
    environment:
      - POSTGRES_DB=dj_movie  # Database name 
      - POSTGRES_USER=admin  # Database user 
      - POSTGRES_PASSWORD=postgres  # Database password 
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist database data
volumes:
  postgres_data:  # Named volume for persistent database storage
